### ISSUE TITLE
北邮生存手册 v2022

### ISSUE THREAD

**Issue by lin594** [BUPTSE/welcome#1]
搬运自 https://shimo.im/docs/d9YXgKTT9JCQ9rtR
搬运进度：
- [x] 新生报到
- [x] 校区相关
- [x] 住宿相关
- [x] #2
- [x] #3
- [x] #5
- [x] #4
- [x] #7
- [x] #6

为避免重复劳动，搬运之前将 对应的 issue 分配给自己（如果没有权限的话评论一下就行）

**Comment by PersicaMoe** [comment]
主要部分已基本完成
