### ISSUE TITLE
宿舍电脑尺寸

### ISSUE THREAD

**Issue by lin594** [BUPTSE/welcome#18]
https://github.com/BUPTSE/welcome/blob/dde7fba3f6bd04e760bc70e3c0b16ef008df80a8/tex/dormitory.tex#L55

横屏的话，雁南可以达到32寸
竖屏的话，忘记了 @PersicaMoe 之前整过？

不过也写一下”考虑一下回本部之后的事情“

**Comment by zyh-hehe** [comment]
竖屏好像稍微有点吃力，27的竖过来应该就到顶了

**Comment by lin594** [comment]
哦对 要写一下 那个老图片是雁北的尺寸

雁南其实会更大一些）

**Comment by PersicaMoe** [comment]
比27寸还大的话就几乎没有什么空隙了，不是很实用

然后不同宿舍的柜子尺寸略有不同里面也有说
