### ISSUE TITLE
军训时间

### ISSUE THREAD

**Issue by JackyTang1** [BUPTSE/welcome#21]
https://github.com/BUPTSE/welcome/blob/005849d618a80d4c7a6f25ddc3b085b44fd8dc74/tex/military-training.tex#L5

预计军训时间：依照北京市教育委员会的统一要求，自 2022 级新生开始，军事技能训练（军训）调整为【第二学期结束后暑假】时间进行

**Comment by lin594** [comment]
诶 那看来之前没有看错啊）
（到底我是在北邮的哪一份文件里看到这件事的呢x）
